/* SPDX-License-Identifier: MIT */
/* SPDX-FileCopyrightText: 2026 Zak Noble-Clarke */
#ifndef MX_VERSIONS_H
#define MX_VERSIONS_H

#include <stdint.h>

#define MXGPU_PROTOCOL_VERSION_MAJOR 1u
#define MXGPU_PROTOCOL_VERSION_MINOR 31u
#define MXGPU_PROTOCOL_VERSION_MINIMUM_MINOR 0u
#define MXGPU_TRANSPORT_VERSION_MAJOR 1u
#define MXGPU_TRANSPORT_VERSION_MINOR 0u

#define MXGPU_PROTOCOL_DYNAMIC_MODE_MINOR 1u
#define MXGPU_PROTOCOL_RESOURCE_PLACEMENT_MINOR 2u
#define MXGPU_PROTOCOL_COLOR_CLEAR_MINOR 3u
#define MXGPU_PROTOCOL_FLOAT_COLOR_FORMAT_MINOR 4u
#define MXGPU_PROTOCOL_RESOURCE_COPY_MINOR 5u
#define MXGPU_PROTOCOL_EXTENDED_PIPELINE_MINOR 6u
#define MXGPU_PROTOCOL_GEOMETRY_TESSELLATION_MINOR 7u
#define MXGPU_PROTOCOL_SRGB_FORMAT_MINOR 8u
#define MXGPU_PROTOCOL_TEXTURE_VIEW_LEVELS_MINOR 9u
#define MXGPU_PROTOCOL_VIEWPORT_Y_FLIP_MINOR 10u
#define MXGPU_PROTOCOL_EXTENDED_PIXEL_FORMAT_MINOR 11u
#define MXGPU_PROTOCOL_TEXTURE_COMPARE_MINOR 12u
#define MXGPU_PROTOCOL_FLOAT_BUFFER_FORMAT_MINOR 13u
#define MXGPU_PROTOCOL_DEPTH24_STENCIL8_MINOR 14u
#define MXGPU_PROTOCOL_PRIMITIVE_RESTART_MINOR 15u
#define MXGPU_PROTOCOL_TEXTURE_ARRAY_MINOR 16u
#define MXGPU_PROTOCOL_TRANSFER_LIMIT_MINOR 17u
#define MXGPU_PROTOCOL_PRESENT_SOURCE_OVERRIDE_MINOR 18u
#define MXGPU_PROTOCOL_GPU_MMU_MINOR 19u
#define MXGPU_PROTOCOL_PRESENT_OPAQUE_XRGB_MINOR 20u
#define MXGPU_PROTOCOL_VBLANK_MINOR 21u
#define MXGPU_PROTOCOL_QUEUE_RESET_MINOR 22u
#define MXGPU_PROTOCOL_SCANOUT_APERTURE_MINOR 23u
#define MXGPU_PROTOCOL_VOLUME_TEXTURE_MINOR 24u
#define MXGPU_PROTOCOL_INTEGER_PIXEL_FORMAT_MINOR 25u
#define MXGPU_PROTOCOL_RASTER_ORDER_GROUP_MINOR 26u
#define MXGPU_PROTOCOL_BUFFER_FILL_MINOR 27u
#define MXGPU_PROTOCOL_TEXTURE_DIMENSION_BINDING_MINOR 28u
#define MXGPU_PROTOCOL_COMPUTE_LIMIT_MINOR 29u
#define MXGPU_PROTOCOL_RESOURCE_ARRAY_MINOR 30u
#define MXGPU_PROTOCOL_REGISTER_SPACE_BINDING_MINOR 31u

#define MXSB_VERSION_MAJOR 1u
#define MXSB_VERSION_MINOR 72u

#define MX_PCI_VENDOR_ID 0x4d58u
#define MXGPU_PCI_DEVICE_ID 0x4750u
#define MXGPU_PCI_SUBSYSTEM_VENDOR_ID 0x4d58u
#define MXGPU_PCI_SUBSYSTEM_DEVICE_ID 0x4750u
#define MXGPU_PCI_REVISION_ID 0x00u
#define MXGPU_PCI_CLASS_CODE 0x038000u

#define MXGA_PROTOCOL_MAJOR 1u
#define MXGA_PROTOCOL_MINOR 6u
#define MXGA_MAGIC 0x4147584du

#define MXGA_PCI_DEVICE_ID 0x4147u
#define MXGA_PCI_SUBSYSTEM_DEVICE_ID 0x4147u
#define MXGA_PCI_REVISION_ID 0x01u
#define MXGA_PCI_CLASS_CODE 0x088000u

#define MXGPU_PROTOCOL_MAGIC 0x5047584du
#define MXSB_MAGIC 0x4d585342u

#endif
