/* SPDX-License-Identifier: MIT */
/* SPDX-FileCopyrightText: 2026 Zak Noble-Clarke */
#ifndef MXGPU_TRANSPORT_ABI_H
#define MXGPU_TRANSPORT_ABI_H

#include <stdint.h>

#define MXGPU_REGISTER_BAR_SIZE 0x400u
#define MXGPU_FRAMEBUFFER_BAR_INDEX 2u
#define MXGPU_FRAMEBUFFER_BAR_SIZE 0x04000000ull

#define MXGPU_REG_STATUS 0x000u
#define MXGPU_REG_DEVICE_GENERATION 0x004u
#define MXGPU_REG_IRQ_STATUS 0x008u
#define MXGPU_REG_IRQ_MASK 0x00cu
#define MXGPU_REG_CONTROL 0x010u
#define MXGPU_REG_MAGIC 0x014u
#define MXGPU_REG_TRANSPORT_VERSION 0x018u
#define MXGPU_REG_NEGOTIATION_REQUEST_LOW 0x020u
#define MXGPU_REG_NEGOTIATION_REQUEST_HIGH 0x024u
#define MXGPU_REG_NEGOTIATION_RESPONSE_LOW 0x028u
#define MXGPU_REG_NEGOTIATION_RESPONSE_HIGH 0x02cu
#define MXGPU_REG_MODE_REQUEST_SEQUENCE 0x030u
#define MXGPU_REG_MODE_REQUEST_DEVICE_GENERATION 0x034u
#define MXGPU_REG_MODE_REQUEST_TARGET 0x038u
#define MXGPU_REG_MODE_REQUEST_WIDTH 0x03cu
#define MXGPU_REG_MODE_REQUEST_HEIGHT 0x040u
#define MXGPU_REG_MODE_REQUEST_REFRESH_MILLIHZ 0x044u
#define MXGPU_REG_MODE_REQUEST_ACK 0x048u
#define MXGPU_MODE_REQUEST_TARGET_SCANOUT_MASK 0x0000ffffu
#define MXGPU_MODE_REQUEST_TARGET_FLAGS_MASK 0xffff0000u

#define MXGPU_QUEUE_REGISTER_BASE 0x100u
#define MXGPU_QUEUE_REGISTER_STRIDE 0x40u
#define MXGPU_QREG_DESCRIPTOR_LOW 0x00u
#define MXGPU_QREG_DESCRIPTOR_HIGH 0x04u
#define MXGPU_QREG_AVAILABLE_LOW 0x08u
#define MXGPU_QREG_AVAILABLE_HIGH 0x0cu
#define MXGPU_QREG_USED_LOW 0x10u
#define MXGPU_QREG_USED_HIGH 0x14u
#define MXGPU_QREG_SIZE 0x18u
#define MXGPU_QREG_ENABLE 0x1cu
#define MXGPU_QREG_PRODUCER_TAIL 0x20u
#define MXGPU_QREG_SUBMISSION_HEAD 0x24u
#define MXGPU_QREG_USED_TAIL 0x28u
#define MXGPU_QREG_USED_CONSUMER 0x2cu
#define MXGPU_QREG_FAULT 0x30u

#define MXGPU_VBLANK_REGISTER_BASE 0x280u
#define MXGPU_VBLANK_REGISTER_STRIDE 0x10u
#define MXGPU_VBLANK_REGISTER_COUNT 16u
#define MXGPU_VBREG_FRAME 0x00u
#define MXGPU_VBLANK_FRAME_TARGET_MASK 0x0000ffffu
#define MXGPU_VBLANK_FRAME_COUNTER_MASK 0xffff0000u
#define MXGPU_VBLANK_FRAME_COUNTER_SHIFT 16u
#define MXGPU_VBLANK_FRAME_COUNTER_MODULUS 0x10000u
#define MXGPU_VBLANK_TARGET_NONE 0xffffu

#define MXGPU_APERTURE_REGISTER_BASE 0x380u
#define MXGPU_APERTURE_REGISTER_SIZE 0x40u
#define MXGPU_AREG_BASE_LOW 0x00u
#define MXGPU_AREG_BASE_HIGH 0x04u
#define MXGPU_AREG_SIZE 0x08u
#define MXGPU_AREG_STRIDE 0x0cu
#define MXGPU_AREG_WIDTH 0x10u
#define MXGPU_AREG_HEIGHT 0x14u
#define MXGPU_AREG_FORMAT 0x18u
#define MXGPU_AREG_TARGET 0x1cu
#define MXGPU_AREG_CONTROL 0x20u
#define MXGPU_AREG_STATUS 0x24u
#define MXGPU_AREG_POWER_ON_BASE_LOW 0x28u
#define MXGPU_AREG_POWER_ON_BASE_HIGH 0x2cu
#define MXGPU_AREG_POWER_ON_STRIDE 0x30u
#define MXGPU_AREG_POWER_ON_WIDTH 0x34u
#define MXGPU_AREG_POWER_ON_HEIGHT 0x38u
#define MXGPU_AREG_POWER_ON_FORMAT 0x3cu
#define MXGPU_RESERVATION_REGISTER_BASE 0x3c0u
#define MXGPU_RESERVATION_REGISTER_SIZE 0x40u
#define MXGPU_RREG_BASE_LOW 0x00u
#define MXGPU_RREG_BASE_HIGH 0x04u
#define MXGPU_RREG_SIZE 0x08u
#define MXGPU_APERTURE_CONTROL_ARM (1u << 0)
#define MXGPU_APERTURE_CONTROL_DISARM (1u << 1)
#define MXGPU_APERTURE_CONTROL_REFRESH (1u << 2)
#define MXGPU_APERTURE_CONTROL_KNOWN_MASK (MXGPU_APERTURE_CONTROL_ARM | MXGPU_APERTURE_CONTROL_DISARM | MXGPU_APERTURE_CONTROL_REFRESH)
#define MXGPU_APERTURE_STATUS_SUPPORTED (1u << 0)
#define MXGPU_APERTURE_STATUS_ARMED (1u << 1)
#define MXGPU_APERTURE_STATUS_FAULT_SHIFT 8u
#define MXGPU_APERTURE_STATUS_FAULT_MASK (0xffu << MXGPU_APERTURE_STATUS_FAULT_SHIFT)
#define MXGPU_APERTURE_STATUS_KNOWN_MASK (MXGPU_APERTURE_STATUS_SUPPORTED | MXGPU_APERTURE_STATUS_ARMED | MXGPU_APERTURE_STATUS_FAULT_MASK)
#define MXGPU_APERTURE_FORMAT_NONE 0u
#define MXGPU_APERTURE_BASE_ALIGNMENT 0x1000ull
#define MXGPU_MAX_APERTURE_EDGE 8192u
#define MXGPU_APERTURE_BYTES_PER_PIXEL 4u
#define MXGPU_MAX_APERTURE_BYTES (MXGPU_MAX_APERTURE_EDGE * MXGPU_MAX_APERTURE_EDGE * MXGPU_APERTURE_BYTES_PER_PIXEL)
#define MXGPU_APERTURE_FAULT_NONE 0u
#define MXGPU_APERTURE_FAULT_NOT_NEGOTIATED 1u
#define MXGPU_APERTURE_FAULT_INVALID_BASE 2u
#define MXGPU_APERTURE_FAULT_INVALID_GEOMETRY 3u
#define MXGPU_APERTURE_FAULT_UNSUPPORTED_FORMAT 4u
#define MXGPU_APERTURE_FAULT_RANGE_TOO_LARGE 5u
#define MXGPU_APERTURE_FAULT_UNKNOWN_TARGET 6u
#define MXGPU_APERTURE_FAULT_INVALID_CONTROL 7u
#define MXGPU_APERTURE_FAULT_MEMORY 8u

#define MXGPU_CONTROL_NEGOTIATE (1u << 0)
#define MXGPU_CONTROL_RESET (1u << 1)
#define MXGPU_CONTROL_KNOWN_MASK (MXGPU_CONTROL_NEGOTIATE | MXGPU_CONTROL_RESET)

#define MXGPU_STATUS_NEGOTIATED (1u << 0)
#define MXGPU_STATUS_RESET_REQUIRED (1u << 1)
#define MXGPU_STATUS_TRANSPORT_FAULT (1u << 2)
#define MXGPU_STATUS_IRQ_ASSERTED (1u << 3)

#define MXGPU_IRQ_COMPLETION (1u << 0)
#define MXGPU_IRQ_NEGOTIATION (1u << 1)
#define MXGPU_IRQ_QUEUE_FAULT (1u << 2)
#define MXGPU_IRQ_TRANSPORT_FAULT (1u << 3)
#define MXGPU_IRQ_MODE_CHANGE (1u << 4)
#define MXGPU_IRQ_VBLANK (1u << 5)
#define MXGPU_IRQ_KNOWN_MASK                                                                       \
    (MXGPU_IRQ_COMPLETION | MXGPU_IRQ_NEGOTIATION | MXGPU_IRQ_QUEUE_FAULT |                        \
     MXGPU_IRQ_TRANSPORT_FAULT | MXGPU_IRQ_MODE_CHANGE | MXGPU_IRQ_VBLANK)

#define MXGPU_AVAILABLE_ENTRY_SIZE 4u
#define MXGPU_USED_ENTRY_SIZE 16u
#define MXGPU_QUEUE_COUNT 6u
#define MXGPU_QUEUE_DESCRIPTOR_SIZE 16u

#define MXGPU_DESC_NEXT (1u << 0)
#define MXGPU_DESC_DEVICE_WRITE (1u << 1)

#define MXGPU_QUEUE_CONTROL 0u
#define MXGPU_QUEUE_RENDER 1u
#define MXGPU_QUEUE_COMPUTE 2u
#define MXGPU_QUEUE_TRANSFER 3u
#define MXGPU_QUEUE_CURSOR 4u
#define MXGPU_QUEUE_PAGING 5u

#define MXGPU_QUEUE_FAULT_NONE 0u
#define MXGPU_QUEUE_FAULT_INVALID_CONFIGURATION 1u
#define MXGPU_QUEUE_FAULT_NOT_NEGOTIATED 2u
#define MXGPU_QUEUE_FAULT_PRODUCER_OUT_OF_RANGE 3u
#define MXGPU_QUEUE_FAULT_USED_CONSUMER_OUT_OF_RANGE 4u
#define MXGPU_QUEUE_FAULT_AVAILABLE_RING_DMA 5u
#define MXGPU_QUEUE_FAULT_INVALID_AVAILABLE_ENTRY 6u
#define MXGPU_QUEUE_FAULT_DESCRIPTOR_DMA 7u
#define MXGPU_QUEUE_FAULT_INVALID_DESCRIPTOR 8u
#define MXGPU_QUEUE_FAULT_DESCRIPTOR_CYCLE 9u
#define MXGPU_QUEUE_FAULT_DESCRIPTOR_IN_USE 10u
#define MXGPU_QUEUE_FAULT_DESCRIPTOR_DIRECTION 11u
#define MXGPU_QUEUE_FAULT_COMMAND_TOO_LARGE 12u
#define MXGPU_QUEUE_FAULT_COMPLETION_BUFFER_MISSING 13u
#define MXGPU_QUEUE_FAULT_COMPLETION_DMA 14u
#define MXGPU_QUEUE_FAULT_USED_RING_DMA 15u
#define MXGPU_QUEUE_FAULT_COMPLETION_ORDER 16u
#define MXGPU_QUEUE_FAULT_BACKEND_PROTOCOL 17u
#define MXGPU_QUEUE_FAULT_HOST_ALLOCATION 18u

#endif
